[package]
name = "empirust"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = 2
opt-level = 1

# use all optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3

[dependencies]
tui = "0.19.*"
crossterm = "0.26.*"
mpd = "*"
# time = "*"
